// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygrifzgrsczzeeppedfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlncmlmemdyc2N6emVlcHBlZGZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1OTM3NzUsImV4cCI6MjA1ODE2OTc3NX0.LX6C71TUL-CC8nI8V_0O0em7w9N73fvTqngwQgaekaw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);